CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR2(40),
    PRODUCT_PRICE NUMBER,
    PRODUCT_CNT NUMBER,
    CONSTRAINT PRODUCT_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE ACCOUNT(
    ACCOUNT_ID VARCHAR2(40),
    ACCOUNT_PW VARCHAR2(40),
    ACCOUNT_ADMIN_FLAG VARCHAR2(2),
    CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID)
);
ALTER TABLE ACCOUNT ADD ACCOUNT_ADMIN_FLAG VARCHAR2(2);
CREATE SEQUENCE PRODUCT_PRODUCT_ID
START WITH 100;